allowBuilds:
  cbor-extract: false
  simple-git-hooks: false
  vue-demi: false

catalog:
  sonda: 0.10.1
  vite: 8.0.0-beta.13

enableGlobalVirtualStore: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@oxc-project/*"
  - "@rolldown/*"
  - rolldown
  - rolldown-plugin-dts
  - tsdown
  - unrun
  - vite

overrides:
  eslint: "-"
  vite: "catalog:"

patchedDependencies:
  evlog: patches/evlog.patch

publicHoistPattern:
  - nitro*

savePrefix: ""

shellEmulator: true
