allowBuilds:
  cbor-extract: false
  simple-git-hooks: false
  vue-demi: false

dedupePeers: true
dedupePeerDependents: true

catalog:
  "@vue/compiler-sfc": 3.6.0-beta.10
  "@vue/compiler-ssr": 3.6.0-beta.10
  vue: 3.6.0-beta.10

overrides:
  "@vue/compiler-sfc": "catalog:"
  "@vue/compiler-ssr": "catalog:"
  vue: "catalog:"

publicHoistPattern:
  - nitro*

savePrefix: ""

shellEmulator: true
