allowBuilds:
  cbor-extract: false
  simple-git-hooks: false
  vue-demi: false

catalog:
  "@vue/compiler-sfc": 3.6.0-beta.10
  "@vue/compiler-ssr": 3.6.0-beta.10
  vue: 3.6.0-beta.10

dedupePeerDependents: true
dedupePeers: true

overrides:
  "@vue/compiler-sfc": "catalog:"
  "@vue/compiler-ssr": "catalog:"
  rolldown: 1.0.0-rc.18
  vue: "catalog:"

patchedDependencies:
  evlog: patches/evlog.patch

publicHoistPattern:
  - nitro*

savePrefix: ""

shellEmulator: true
